version: 3
services:
  front_end:
    build: ./Client
    image: FrontEnd
    ports:
      - "8081:3000"
  back_end:
    build: ./Server
    image: BackEnd
    ports:
      - "8082:5000"
    depends_on:
      - db_relational
      - db_time_series
  gps_module:
    build: GPS
    image: GPSmodule
    ports:
      - "8083:5555"
  db_relational:
    build: ./database/relational
    image: DBrelational
    expose:
      - "33060"
    volumes:
      - $HOME/database/relational/data:/var/lib/mysql
  db_time_series:
    build: ./database/time_series
    image: DBtime_series
    expose:
      - "8086"
    volumes:
      - $HOME/database/time_series/data:/var/lib/influxdb
