version: "3"
services:
  front_end:
    build: ./Client
    image: frontend
    ports:
      - "8081:3000"
  back_end:
    build: ./Server
    image: backend
    ports:
      - "8082:5000"
    depends_on:
      - db_relational
      - db_time_series
  gps_module:
    build: GPS
    image: gpsmodule
    ports:
      - "8083:5555"
  db_relational:
    build: ./database/relational
    image: dbrelational
    expose:
      - "3306"
    volumes:
      - $HOME/database/relational:/var/lib/mysql
  db_time_series:
    build: ./database/time_series
    image: dbtime_series
    expose:
      - "8086"
    volumes:
      - $HOME/database/time_series:/var/lib/influxdb
