version: 3
services:
  nginx:
    image: nginx
    port:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  front_end:
    ...
  back_end:
    ...
  db_relational:
    build: database/relational
    volumes:
      - $HOME/database/relational/data:/var/lib/mysql
  db_time_series:
    build: database/time_series
    volumes:
      - $HOME/database/time_series/data:/var/lib/influxdb
