version: "3"
services:
  front_end:
    build: Client
    image: front_end
    networks:
      - all
  back_end:
    build: Server
    image: back_end
    networks:
      - all
    depends_on:
      - db_relational
      - db_time_series
  gps_module:
    build: GPS
    image: gps_module
    networks:
      - all
  db_relational:
    build: database/relational
    image: db_relational
    volumes:
      - $HOME/database/relational:/var/lib/mysql
    ports:
      - 8082:3306
    networks:
      - all
  db_time_series:
    build: database/time_series
    image: db_time_series
    volumes:
      - $HOME/database/time_series:/var/lib/influxdb
    networks:
      - all
  nginx:
    image: nginx:1.17.0
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8081:80
    networks:
      - all
    depends_on:
      - front_end
      - back_end
      - gps_module

networks:
  all:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16
