version: "3"
services:
  front_end:
    build: ./Client
    image: frontend
    ports:
      - "8081:3000"
    networks:
      - all
  back_end:
    build: ./Server
    image: backend
    ports:
      - "8082:5000"
    networks:
      - all
    depends_on:
      - db_relational
      - db_time_series
  gps_module:
    build: GPS
    image: gpsmodule
    ports:
      - "8083:5555"
    networks:
      - all
  db_relational:
    build: ./database/relational
    image: dbrelational
    volumes:
      - $HOME/database/relational:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - all
  db_time_series:
    build: ./database/time_series
    image: dbtime_series
    volumes:
      - $HOME/database/time_series:/var/lib/influxdb
    expose:
      - "8086"
    networks:
      - all

networks:
  all:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/16
